from Cola import *

if __name__=='__main__':
    cola = Cola_Secuencial(5)
    cola.Insertar(1)
    cola.Insertar(2)
    cola.Insertar(3)
    cola.Insertar(4)
    cola.Insertar(5)
    print("antes de suprimir")
    cola.Recorrer()
    cola.Suprimir()
    cola.Suprimir()
    print("despues de suprimir")
    cola.Recorrer()
    colaloca = Cola_Encadenada()
    colaloca.Insertar(1)
    colaloca.Insertar(2)
    colaloca.Insertar(3)
    colaloca.Insertar(4)
    colaloca.Insertar(5)
    print("antes de suprimir")
    colaloca.Recorrer()
    colaloca.Suprimir()
    colaloca.Suprimir()
    print("despues de suprimir")
    colaloca.Recorrer()